import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './layout/Header.js'
import Blog from './layout/Blog'
import Footer from './layout/Footer'
import Api from './Api'
import Post from './post'
import { useEffect, useState } from 'react'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>GCO blog Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='max-w-[1230px] mx-auto'>
          <Header/>
          <Blog/>
          <Footer/>
          <Api/>
      </main>
      <Post/>
    </div>
  )
}
